export type IndianRegion = 'North' | 'South' | 'East' | 'West' | 'Central' | 'North-East' | 'Islands';
export type AdministrativeType = 'State' | 'Union Territory';

export interface StateForecastDay {
  day: string;
  date: string;
  icon: 'sunny' | 'partly-cloudy' | 'cloudy' | 'rain' | 'thunderstorm' | 'windy' | 'snow';
  high: number;
  low: number;
  rainChance: number;
  rainfall: number;
  condition: string;
}

export interface StateWeatherMetric {
  label: string;
  value: string;
  detail: string;
  icon: 'humidity' | 'wind' | 'pressure' | 'visibility' | 'thermometer';
}

export interface IndianStateWeather {
  id: string;
  name: string;
  hindiName: string;
  country: 'India';
  countryHindi: 'भारत';
  capital: string;
  type: AdministrativeType;
  region: IndianRegion;
  lat: number;
  lng: number;
  temperature: number;
  feelsLike: number;
  high: number;
  low: number;
  condition: string;
  icon: 'sunny' | 'partly-cloudy' | 'cloudy' | 'rain' | 'thunderstorm' | 'windy' | 'snow';
  humidity: number;
  windSpeed: number;
  windDirection: string;
  pressure: number;
  visibility: number;
  rainChance: number;
  uvIndex: number;
  airQuality: {
    aqi: number;
    status: 'Good' | 'Moderate' | 'Poor' | 'Very Poor' | 'Severe';
  };
  alert?: {
    severity: 'high' | 'moderate' | 'information';
    title: string;
    description: string;
  };
  todaySummary: string;
  metrics: StateWeatherMetric[];
  forecast: StateForecastDay[];
}

export const ALL_INDIAN_STATES_WEATHER: IndianStateWeather[] = [
  // --- 28 STATES OF INDIA ---
  {
    id: 'andhra-pradesh',
    name: 'Andhra Pradesh',
    hindiName: 'आंध्र प्रदेश',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Amaravati / Visakhapatnam',
    type: 'State',
    region: 'South',
    lat: 16.5417,
    lng: 80.5158,
    temperature: 33,
    feelsLike: 38,
    high: 35,
    low: 26,
    condition: 'Humid & Passing Showers',
    icon: 'rain',
    humidity: 78,
    windSpeed: 18,
    windDirection: 'ESE',
    pressure: 1006,
    visibility: 7.5,
    rainChance: 45,
    uvIndex: 8,
    airQuality: { aqi: 68, status: 'Moderate' },
    alert: {
      severity: 'moderate',
      title: 'Coastal Swell & Squall Advisory',
      description: 'Fishermen along coastal Andhra advised caution due to moderate offshore squalls.',
    },
    todaySummary: 'Warm tropical conditions with high humidity and scattered coastal showers late afternoon.',
    metrics: [
      { label: 'Humidity', value: '78%', detail: 'Tropical moisture high', icon: 'humidity' },
      { label: 'Wind speed', value: '18 km/h', detail: 'ESE sea breeze active', icon: 'wind' },
      { label: 'Barometer', value: '1006 hPa', detail: 'Slight low pressure', icon: 'pressure' },
      { label: 'Visibility', value: '7.5 km', detail: 'Hazy near coastline', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High midday', icon: 'thermometer' },
      { label: 'Rain chance', value: '45%', detail: 'Evening showers likely', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 35, low: 26, rainChance: 45, rainfall: 6.2, condition: 'Passing Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'partly-cloudy', high: 34, low: 25, rainChance: 40, rainfall: 4.5, condition: 'Scattered Clouds' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 33, low: 25, rainChance: 65, rainfall: 14.0, condition: 'Moderate Rain' },
      { day: 'Sat', date: '13 Sep', icon: 'thunderstorm', high: 31, low: 24, rainChance: 75, rainfall: 22.0, condition: 'Thunderstorms' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 33, low: 25, rainChance: 30, rainfall: 2.0, condition: 'Warm & Humid' },
    ],
  },
  {
    id: 'arunachal-pradesh',
    name: 'Arunachal Pradesh',
    hindiName: 'अरुणाचल प्रदेश',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Itanagar',
    type: 'State',
    region: 'North-East',
    lat: 27.0844,
    lng: 93.6053,
    temperature: 23,
    feelsLike: 23,
    high: 25,
    low: 17,
    condition: 'Mountain Rain Spells',
    icon: 'rain',
    humidity: 88,
    windSpeed: 10,
    windDirection: 'NE',
    pressure: 1010,
    visibility: 6.0,
    rainChance: 70,
    uvIndex: 5,
    airQuality: { aqi: 24, status: 'Good' },
    alert: {
      severity: 'moderate',
      title: 'Himalayan Slope Soil Saturation',
      description: 'Localized debris fall warning on mountain passes between Bhalukpong and Tawang.',
    },
    todaySummary: 'Cool mountain climate with intermittent spells of rain and persistent cloud cover across valleys.',
    metrics: [
      { label: 'Humidity', value: '88%', detail: 'High valley saturation', icon: 'humidity' },
      { label: 'Wind speed', value: '10 km/h', detail: 'Gentle montane draft', icon: 'wind' },
      { label: 'Barometer', value: '1010 hPa', detail: 'Stable ridge level', icon: 'pressure' },
      { label: 'Visibility', value: '6.0 km', detail: 'Mountain mist', icon: 'visibility' },
      { label: 'UV Index', value: '5 of 11', detail: 'Moderate filtered', icon: 'thermometer' },
      { label: 'Rain chance', value: '70%', detail: 'Steady showers', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 25, low: 17, rainChance: 70, rainfall: 16.5, condition: 'Mountain Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 24, low: 16, rainChance: 80, rainfall: 24.0, condition: 'Heavy Showers' },
      { day: 'Fri', date: '12 Sep', icon: 'cloudy', high: 26, low: 17, rainChance: 50, rainfall: 8.0, condition: 'Overcast Ridge' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 27, low: 18, rainChance: 35, rainfall: 3.0, condition: 'Partly Sunny' },
      { day: 'Sun', date: '14 Sep', icon: 'rain', high: 25, low: 17, rainChance: 60, rainfall: 12.0, condition: 'Scattered Rain' },
    ],
  },
  {
    id: 'assam',
    name: 'Assam',
    hindiName: 'असम',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Dispur / Guwahati',
    type: 'State',
    region: 'North-East',
    lat: 26.1445,
    lng: 91.7362,
    temperature: 28,
    feelsLike: 33,
    high: 31,
    low: 24,
    condition: 'Heavy Rain / Brahmaputra Watch',
    icon: 'rain',
    humidity: 91,
    windSpeed: 16,
    windDirection: 'E',
    pressure: 1005,
    visibility: 5.5,
    rainChance: 85,
    uvIndex: 6,
    airQuality: { aqi: 36, status: 'Good' },
    alert: {
      severity: 'high',
      title: 'Brahmaputra Basin Flood Watch',
      description: 'Rising water levels in Dhubri and Majuli. Water logging and riverbank vigilance active.',
    },
    todaySummary: 'Monsoon surge bringing persistent rainfall along river plains. Keep alert on low-lying districts.',
    metrics: [
      { label: 'Humidity', value: '91%', detail: 'Near saturation', icon: 'humidity' },
      { label: 'Wind speed', value: '16 km/h', detail: 'Moist easterly', icon: 'wind' },
      { label: 'Barometer', value: '1005 hPa', detail: 'Monsoon depression', icon: 'pressure' },
      { label: 'Visibility', value: '5.5 km', detail: 'Reduced in rain', icon: 'visibility' },
      { label: 'UV Index', value: '6 of 11', detail: 'Moderate cloud cover', icon: 'thermometer' },
      { label: 'Rain chance', value: '85%', detail: 'Widespread rain', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 31, low: 24, rainChance: 85, rainfall: 32.0, condition: 'Heavy Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 30, low: 24, rainChance: 80, rainfall: 28.5, condition: 'Monsoon Spells' },
      { day: 'Fri', date: '12 Sep', icon: 'thunderstorm', high: 29, low: 23, rainChance: 75, rainfall: 20.0, condition: 'Thunderstorm' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 32, low: 24, rainChance: 45, rainfall: 6.0, condition: 'Breaks in Cloud' },
      { day: 'Sun', date: '14 Sep', icon: 'rain', high: 31, low: 24, rainChance: 60, rainfall: 14.0, condition: 'Passing Showers' },
    ],
  },
  {
    id: 'bihar',
    name: 'Bihar',
    hindiName: 'बिहार',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Patna',
    type: 'State',
    region: 'East',
    lat: 25.5941,
    lng: 85.1376,
    temperature: 32,
    feelsLike: 37,
    high: 34,
    low: 26,
    condition: 'Partly Cloudy & Humid',
    icon: 'partly-cloudy',
    humidity: 74,
    windSpeed: 12,
    windDirection: 'ESE',
    pressure: 1007,
    visibility: 7.0,
    rainChance: 35,
    uvIndex: 8,
    airQuality: { aqi: 115, status: 'Moderate' },
    todaySummary: 'Warm and humid Gangetic plains conditions with sunny interludes and isolated thundershowers.',
    metrics: [
      { label: 'Humidity', value: '74%', detail: 'Subtropical humidity', icon: 'humidity' },
      { label: 'Wind speed', value: '12 km/h', detail: 'Light easterly breeze', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Normal Gangetic range', icon: 'pressure' },
      { label: 'Visibility', value: '7.0 km', detail: 'Slight haze', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High midday', icon: 'thermometer' },
      { label: 'Rain chance', value: '35%', detail: 'Isolated thunder', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 34, low: 26, rainChance: 35, rainfall: 2.8, condition: 'Partly Cloudy' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 33, low: 25, rainChance: 55, rainfall: 9.5, condition: 'Scattered Showers' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 32, low: 25, rainChance: 65, rainfall: 15.0, condition: 'Rain Spells' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 35, low: 26, rainChance: 20, rainfall: 0.5, condition: 'Warm & Sunny' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 35, low: 26, rainChance: 25, rainfall: 1.0, condition: 'Partly Cloudy' },
    ],
  },
  {
    id: 'chhattisgarh',
    name: 'Chhattisgarh',
    hindiName: 'छत्तीसगढ़',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Raipur',
    type: 'State',
    region: 'Central',
    lat: 21.2514,
    lng: 81.6296,
    temperature: 30,
    feelsLike: 34,
    high: 32,
    low: 24,
    condition: 'Scattered Monsoon Clouds',
    icon: 'cloudy',
    humidity: 79,
    windSpeed: 14,
    windDirection: 'S',
    pressure: 1008,
    visibility: 8.0,
    rainChance: 50,
    uvIndex: 7,
    airQuality: { aqi: 72, status: 'Moderate' },
    todaySummary: 'Favorable agricultural conditions with good soil moisture and passing rain across central districts.',
    metrics: [
      { label: 'Humidity', value: '79%', detail: 'Favorable crop moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '14 km/h', detail: 'Southerly breeze', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Normal', icon: 'pressure' },
      { label: 'Visibility', value: '8.0 km', detail: 'Clear', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '50%', detail: 'Afternoon rain', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'cloudy', high: 32, low: 24, rainChance: 50, rainfall: 7.5, condition: 'Scattered Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 31, low: 23, rainChance: 65, rainfall: 14.0, condition: 'Monsoon Rain' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 30, low: 23, rainChance: 70, rainfall: 18.0, condition: 'Rain Spells' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 32, low: 24, rainChance: 35, rainfall: 3.0, condition: 'Scattered Clouds' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 33, low: 24, rainChance: 20, rainfall: 0.0, condition: 'Mostly Sunny' },
    ],
  },
  {
    id: 'goa',
    name: 'Goa',
    hindiName: 'गोवा',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Panaji',
    type: 'State',
    region: 'West',
    lat: 15.4909,
    lng: 73.8278,
    temperature: 29,
    feelsLike: 33,
    high: 30,
    low: 25,
    condition: 'Coastal Showers & Breezy',
    icon: 'rain',
    humidity: 86,
    windSpeed: 24,
    windDirection: 'WSW',
    pressure: 1007,
    visibility: 7.0,
    rainChance: 65,
    uvIndex: 7,
    airQuality: { aqi: 32, status: 'Good' },
    todaySummary: 'Pleasant coastal monsoon climate with moderate sea breeze and intermittent coastal showers.',
    metrics: [
      { label: 'Humidity', value: '86%', detail: 'Maritime humid', icon: 'humidity' },
      { label: 'Wind speed', value: '24 km/h', detail: 'WSW coastal gust', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Arabian sea trough', icon: 'pressure' },
      { label: 'Visibility', value: '7.0 km', detail: 'Slight spray', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '65%', detail: 'Passing bands', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 30, low: 25, rainChance: 65, rainfall: 12.0, condition: 'Coastal Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 29, low: 24, rainChance: 70, rainfall: 16.0, condition: 'Wet Spells' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 31, low: 25, rainChance: 40, rainfall: 4.0, condition: 'Breezy & Sun' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 31, low: 25, rainChance: 30, rainfall: 2.0, condition: 'Sunny Breaks' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 32, low: 26, rainChance: 20, rainfall: 0.0, condition: 'Clear Skies' },
    ],
  },
  {
    id: 'gujarat',
    name: 'Gujarat',
    hindiName: 'गुजरात',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Gandhinagar / Ahmedabad',
    type: 'State',
    region: 'West',
    lat: 23.2156,
    lng: 72.6369,
    temperature: 34,
    feelsLike: 37,
    high: 36,
    low: 26,
    condition: 'Dry & Clear Skies',
    icon: 'sunny',
    humidity: 52,
    windSpeed: 15,
    windDirection: 'WNW',
    pressure: 1008,
    visibility: 9.0,
    rainChance: 10,
    uvIndex: 9,
    airQuality: { aqi: 88, status: 'Moderate' },
    todaySummary: 'Bright sunny day with low precipitation risk and warm westerly winds across Saurashtra and central plains.',
    metrics: [
      { label: 'Humidity', value: '52%', detail: 'Moderate comfortable', icon: 'humidity' },
      { label: 'Wind speed', value: '15 km/h', detail: 'WNW breeze', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Stable', icon: 'pressure' },
      { label: 'Visibility', value: '9.0 km', detail: 'Good visibility', icon: 'visibility' },
      { label: 'UV Index', value: '9 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '10%', detail: 'Dry conditions', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'sunny', high: 36, low: 26, rainChance: 10, rainfall: 0.0, condition: 'Sunny & Warm' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 37, low: 26, rainChance: 10, rainfall: 0.0, condition: 'Clear Sky' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 36, low: 25, rainChance: 20, rainfall: 0.5, condition: 'Passing Clouds' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 35, low: 25, rainChance: 25, rainfall: 1.5, condition: 'Scattered Clouds' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 36, low: 26, rainChance: 15, rainfall: 0.0, condition: 'Dry & Sunny' },
    ],
  },
  {
    id: 'haryana',
    name: 'Haryana',
    hindiName: 'हरियाणा',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Chandigarh',
    type: 'State',
    region: 'North',
    lat: 29.0588,
    lng: 76.0856,
    temperature: 33,
    feelsLike: 36,
    high: 36,
    low: 25,
    condition: 'Partly Cloudy & Warm',
    icon: 'partly-cloudy',
    humidity: 58,
    windSpeed: 14,
    windDirection: 'NW',
    pressure: 1009,
    visibility: 7.5,
    rainChance: 20,
    uvIndex: 8,
    airQuality: { aqi: 135, status: 'Moderate' },
    todaySummary: 'Agricultural heartland experiencing warm late-monsoon warmth with good harvest weather.',
    metrics: [
      { label: 'Humidity', value: '58%', detail: 'Moderate', icon: 'humidity' },
      { label: 'Wind speed', value: '14 km/h', detail: 'Dry Northwesterly', icon: 'wind' },
      { label: 'Barometer', value: '1009 hPa', detail: 'High stability', icon: 'pressure' },
      { label: 'Visibility', value: '7.5 km', detail: 'Hazy afternoon', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '20%', detail: 'Isolated drizzle', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 36, low: 25, rainChance: 20, rainfall: 0.8, condition: 'Partly Cloudy' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 37, low: 26, rainChance: 15, rainfall: 0.0, condition: 'Sunny Day' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 34, low: 24, rainChance: 45, rainfall: 5.5, condition: 'Passing Showers' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 35, low: 25, rainChance: 25, rainfall: 1.0, condition: 'Breezy' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 36, low: 25, rainChance: 10, rainfall: 0.0, condition: 'Clear Sky' },
    ],
  },
  {
    id: 'himachal-pradesh',
    name: 'Himachal Pradesh',
    hindiName: 'हिमाचल प्रदेश',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Shimla / Dharamshala',
    type: 'State',
    region: 'North',
    lat: 31.1048,
    lng: 77.1734,
    temperature: 19,
    feelsLike: 19,
    high: 22,
    low: 14,
    condition: 'Crisp Mountain Breeze',
    icon: 'partly-cloudy',
    humidity: 62,
    windSpeed: 11,
    windDirection: 'NNE',
    pressure: 1014,
    visibility: 9.5,
    rainChance: 25,
    uvIndex: 7,
    airQuality: { aqi: 28, status: 'Good' },
    todaySummary: 'Pleasant and brisk hill state weather with clear vistas across the Dhauladhar range.',
    metrics: [
      { label: 'Humidity', value: '62%', detail: 'Clean mountain air', icon: 'humidity' },
      { label: 'Wind speed', value: '11 km/h', detail: 'NNE ridge breeze', icon: 'wind' },
      { label: 'Barometer', value: '1014 hPa', detail: 'High altitude norm', icon: 'pressure' },
      { label: 'Visibility', value: '9.5 km', detail: 'Pristine mountain view', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High mountain sun', icon: 'thermometer' },
      { label: 'Rain chance', value: '25%', detail: 'Light hill shower', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 22, low: 14, rainChance: 25, rainfall: 1.5, condition: 'Brisk & Sun' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 23, low: 13, rainChance: 15, rainfall: 0.0, condition: 'Sunny Mountain' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 20, low: 12, rainChance: 50, rainfall: 8.0, condition: 'Hill Rain' },
      { day: 'Sat', date: '13 Sep', icon: 'cloudy', high: 21, low: 13, rainChance: 35, rainfall: 3.0, condition: 'Cloudy Ridge' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 23, low: 14, rainChance: 10, rainfall: 0.0, condition: 'Clear Horizons' },
    ],
  },
  {
    id: 'jharkhand',
    name: 'Jharkhand',
    hindiName: 'झारखंड',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Ranchi',
    type: 'State',
    region: 'East',
    lat: 23.3441,
    lng: 85.3096,
    temperature: 29,
    feelsLike: 33,
    high: 31,
    low: 23,
    condition: 'Plateau Clouds & Thunder',
    icon: 'thunderstorm',
    humidity: 80,
    windSpeed: 13,
    windDirection: 'SE',
    pressure: 1008,
    visibility: 8.0,
    rainChance: 60,
    uvIndex: 7,
    airQuality: { aqi: 65, status: 'Moderate' },
    todaySummary: 'Chota Nagpur plateau experiencing mild daytime temperatures with afternoon convective clouds.',
    metrics: [
      { label: 'Humidity', value: '80%', detail: 'Humid plateau air', icon: 'humidity' },
      { label: 'Wind speed', value: '13 km/h', detail: 'SE breeze', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Stable', icon: 'pressure' },
      { label: 'Visibility', value: '8.0 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '60%', detail: 'Thunderstorms likely', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'thunderstorm', high: 31, low: 23, rainChance: 60, rainfall: 11.0, condition: 'Thunderstorm' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 30, low: 22, rainChance: 65, rainfall: 15.0, condition: 'Rain Spells' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 31, low: 23, rainChance: 35, rainfall: 4.0, condition: 'Scattered Sun' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 32, low: 23, rainChance: 20, rainfall: 0.5, condition: 'Sunny Intervals' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 32, low: 24, rainChance: 30, rainfall: 2.0, condition: 'Plateau Breeze' },
    ],
  },
  {
    id: 'karnataka',
    name: 'Karnataka',
    hindiName: 'कर्नाटक',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Bengaluru',
    type: 'State',
    region: 'South',
    lat: 12.9716,
    lng: 77.5946,
    temperature: 26,
    feelsLike: 26,
    high: 28,
    low: 20,
    condition: 'Pleasant Breeze & Sun',
    icon: 'partly-cloudy',
    humidity: 64,
    windSpeed: 17,
    windDirection: 'W',
    pressure: 1011,
    visibility: 9.0,
    rainChance: 25,
    uvIndex: 7,
    airQuality: { aqi: 48, status: 'Good' },
    todaySummary: 'Signature pleasant Deccan weather with breezy conditions in Bengaluru and scattered rain on coastal ghats.',
    metrics: [
      { label: 'Humidity', value: '64%', detail: 'Comfortable balance', icon: 'humidity' },
      { label: 'Wind speed', value: '17 km/h', detail: 'Westerly plateau draft', icon: 'wind' },
      { label: 'Barometer', value: '1011 hPa', detail: 'Plateau elevation', icon: 'pressure' },
      { label: 'Visibility', value: '9.0 km', detail: 'Clear', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '25%', detail: 'Evening drizzle', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 28, low: 20, rainChance: 25, rainfall: 2.0, condition: 'Pleasant & Mild' },
      { day: 'Thu', date: '11 Sep', icon: 'partly-cloudy', high: 28, low: 19, rainChance: 30, rainfall: 3.5, condition: 'Passing Clouds' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 27, low: 20, rainChance: 55, rainfall: 10.0, condition: 'Light Showers' },
      { day: 'Sat', date: '13 Sep', icon: 'rain', high: 26, low: 19, rainChance: 60, rainfall: 12.0, condition: 'Ghat Showers' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 28, low: 20, rainChance: 20, rainfall: 1.0, condition: 'Breezy Day' },
    ],
  },
  {
    id: 'kerala',
    name: 'Kerala',
    hindiName: 'केरल',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Thiruvananthapuram / Kochi',
    type: 'State',
    region: 'South',
    lat: 8.5241,
    lng: 76.9366,
    temperature: 28,
    feelsLike: 32,
    high: 30,
    low: 24,
    condition: 'Monsoon Surges & Greenery',
    icon: 'rain',
    humidity: 89,
    windSpeed: 21,
    windDirection: 'WSW',
    pressure: 1007,
    visibility: 7.0,
    rainChance: 80,
    uvIndex: 6,
    airQuality: { aqi: 26, status: 'Good' },
    alert: {
      severity: 'moderate',
      title: 'Vigorous Monsoon Watch',
      description: 'Rough seas along Malabar coast. High swell waves forecast up to 3.2 meters.',
    },
    todaySummary: 'Lush tropical monsoon conditions with steady rain bands and moderate onshore winds.',
    metrics: [
      { label: 'Humidity', value: '89%', detail: 'High marine saturation', icon: 'humidity' },
      { label: 'Wind speed', value: '21 km/h', detail: 'WSW sea winds', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Arabian sea low', icon: 'pressure' },
      { label: 'Visibility', value: '7.0 km', detail: 'Reduced in downpours', icon: 'visibility' },
      { label: 'UV Index', value: '6 of 11', detail: 'Moderate', icon: 'thermometer' },
      { label: 'Rain chance', value: '80%', detail: 'Widespread rain', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 30, low: 24, rainChance: 80, rainfall: 26.0, condition: 'Monsoon Spells' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 29, low: 24, rainChance: 85, rainfall: 34.0, condition: 'Heavy Rain' },
      { day: 'Fri', date: '12 Sep', icon: 'thunderstorm', high: 29, low: 23, rainChance: 75, rainfall: 22.0, condition: 'Squally Showers' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 31, low: 24, rainChance: 45, rainfall: 7.0, condition: 'Breaks in Rain' },
      { day: 'Sun', date: '14 Sep', icon: 'rain', high: 30, low: 24, rainChance: 60, rainfall: 14.0, condition: 'Passing Showers' },
    ],
  },
  {
    id: 'madhya-pradesh',
    name: 'Madhya Pradesh',
    hindiName: 'मध्य प्रदेश',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Bhopal / Indore',
    type: 'State',
    region: 'Central',
    lat: 23.2599,
    lng: 77.4126,
    temperature: 31,
    feelsLike: 34,
    high: 33,
    low: 23,
    condition: 'Partly Cloudy & Warm',
    icon: 'partly-cloudy',
    humidity: 66,
    windSpeed: 13,
    windDirection: 'W',
    pressure: 1009,
    visibility: 8.5,
    rainChance: 30,
    uvIndex: 8,
    airQuality: { aqi: 76, status: 'Moderate' },
    todaySummary: 'Heart of India enjoying balanced late-monsoon warmth with good soybean and pulse crop conditions.',
    metrics: [
      { label: 'Humidity', value: '66%', detail: 'Balanced moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '13 km/h', detail: 'Steady westerly', icon: 'wind' },
      { label: 'Barometer', value: '1009 hPa', detail: 'Normal', icon: 'pressure' },
      { label: 'Visibility', value: '8.5 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '30%', detail: 'Scattered afternoon', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 33, low: 23, rainChance: 30, rainfall: 3.2, condition: 'Partly Cloudy' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 32, low: 23, rainChance: 50, rainfall: 8.0, condition: 'Afternoon Rain' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 31, low: 22, rainChance: 60, rainfall: 14.0, condition: 'Showers' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 34, low: 24, rainChance: 20, rainfall: 0.0, condition: 'Sunny & Bright' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 34, low: 24, rainChance: 25, rainfall: 1.0, condition: 'Warm Breeze' },
    ],
  },
  {
    id: 'maharashtra',
    name: 'Maharashtra',
    hindiName: 'महाराष्ट्र',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Mumbai / Pune',
    type: 'State',
    region: 'West',
    lat: 19.076,
    lng: 72.8777,
    temperature: 30,
    feelsLike: 35,
    high: 32,
    low: 25,
    condition: 'Coastal Showers & High Humidity',
    icon: 'rain',
    humidity: 84,
    windSpeed: 20,
    windDirection: 'SW',
    pressure: 1007,
    visibility: 7.5,
    rainChance: 70,
    uvIndex: 7,
    airQuality: { aqi: 62, status: 'Moderate' },
    alert: {
      severity: 'moderate',
      title: 'Konkan Ghats Rain Alert',
      description: 'Persistent moisture influx over Western Ghats causing localized water logging in low passes.',
    },
    todaySummary: 'Breezy and humid along Konkan coast with sporadic showers in Mumbai, pleasant weather across Deccan plateau.',
    metrics: [
      { label: 'Humidity', value: '84%', detail: 'High marine coastal', icon: 'humidity' },
      { label: 'Wind speed', value: '20 km/h', detail: 'SW monsoon gust', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Trough active', icon: 'pressure' },
      { label: 'Visibility', value: '7.5 km', detail: 'Moderate coastal', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '70%', detail: 'Frequent showers', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 32, low: 25, rainChance: 70, rainfall: 18.0, condition: 'Passing Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 31, low: 25, rainChance: 75, rainfall: 22.0, condition: 'Monsoon Spells' },
      { day: 'Fri', date: '12 Sep', icon: 'thunderstorm', high: 30, low: 24, rainChance: 80, rainfall: 26.0, condition: 'Heavy Rain' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 32, low: 25, rainChance: 40, rainfall: 5.0, condition: 'Breezy & Warm' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 33, low: 26, rainChance: 30, rainfall: 2.0, condition: 'Sunny Breaks' },
    ],
  },
  {
    id: 'manipur',
    name: 'Manipur',
    hindiName: 'मणिपुर',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Imphal',
    type: 'State',
    region: 'North-East',
    lat: 24.817,
    lng: 93.9368,
    temperature: 25,
    feelsLike: 26,
    high: 28,
    low: 19,
    condition: 'Valley Mist & Light Showers',
    icon: 'rain',
    humidity: 83,
    windSpeed: 9,
    windDirection: 'NE',
    pressure: 1010,
    visibility: 7.0,
    rainChance: 60,
    uvIndex: 6,
    airQuality: { aqi: 22, status: 'Good' },
    todaySummary: 'Pleasant valley climate with Loktak lake breeze, light morning mist, and afternoon mountain showers.',
    metrics: [
      { label: 'Humidity', value: '83%', detail: 'Valley moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '9 km/h', detail: 'Gentle breeze', icon: 'wind' },
      { label: 'Barometer', value: '1010 hPa', detail: 'Stable', icon: 'pressure' },
      { label: 'Visibility', value: '7.0 km', detail: 'Mist in valley', icon: 'visibility' },
      { label: 'UV Index', value: '6 of 11', detail: 'Moderate', icon: 'thermometer' },
      { label: 'Rain chance', value: '60%', detail: 'Passing rain', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 28, low: 19, rainChance: 60, rainfall: 9.0, condition: 'Light Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 27, low: 18, rainChance: 65, rainfall: 12.0, condition: 'Scattered Showers' },
      { day: 'Fri', date: '12 Sep', icon: 'cloudy', high: 28, low: 19, rainChance: 40, rainfall: 4.0, condition: 'Overcast' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 29, low: 19, rainChance: 25, rainfall: 1.0, condition: 'Pleasant' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 30, low: 20, rainChance: 20, rainfall: 0.0, condition: 'Sunny Horizons' },
    ],
  },
  {
    id: 'meghalaya',
    name: 'Meghalaya',
    hindiName: 'मेघालय',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Shillong',
    type: 'State',
    region: 'North-East',
    lat: 25.5788,
    lng: 91.8933,
    temperature: 20,
    feelsLike: 20,
    high: 22,
    low: 15,
    condition: 'Abode of Clouds / Continuous Drizzle',
    icon: 'rain',
    humidity: 94,
    windSpeed: 14,
    windDirection: 'S',
    pressure: 1012,
    visibility: 4.5,
    rainChance: 90,
    uvIndex: 4,
    airQuality: { aqi: 18, status: 'Good' },
    alert: {
      severity: 'moderate',
      title: 'Cherrapunji-Mawsynram Heavy Rain Notice',
      description: 'Persistent cloud interception over southern slopes causing high river run-off.',
    },
    todaySummary: 'Classic Meghalaya weather with rolling clouds, heavy mountain mist, and continuous gentle to moderate rain.',
    metrics: [
      { label: 'Humidity', value: '94%', detail: 'Near 100% saturation', icon: 'humidity' },
      { label: 'Wind speed', value: '14 km/h', detail: 'Southerly ridge wind', icon: 'wind' },
      { label: 'Barometer', value: '1012 hPa', detail: 'Plateau pressure', icon: 'pressure' },
      { label: 'Visibility', value: '4.5 km', detail: 'Dense hill fog', icon: 'visibility' },
      { label: 'UV Index', value: '4 of 11', detail: 'Low cloud cover', icon: 'thermometer' },
      { label: 'Rain chance', value: '90%', detail: 'Steady precipitation', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 22, low: 15, rainChance: 90, rainfall: 42.0, condition: 'Continuous Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 21, low: 15, rainChance: 95, rainfall: 56.0, condition: 'Heavy Downpour' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 22, low: 14, rainChance: 85, rainfall: 30.0, condition: 'Monsoon Rain' },
      { day: 'Sat', date: '13 Sep', icon: 'cloudy', high: 23, low: 15, rainChance: 50, rainfall: 8.0, condition: 'Misty Cloud' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 24, low: 16, rainChance: 35, rainfall: 3.0, condition: 'Sunny Breaks' },
    ],
  },
  {
    id: 'mizoram',
    name: 'Mizoram',
    hindiName: 'मिज़ोरम',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Aizawl',
    type: 'State',
    region: 'North-East',
    lat: 23.7271,
    lng: 92.7176,
    temperature: 24,
    feelsLike: 25,
    high: 26,
    low: 18,
    condition: 'Mountain Mist & Passing Rain',
    icon: 'rain',
    humidity: 87,
    windSpeed: 10,
    windDirection: 'S',
    pressure: 1011,
    visibility: 6.5,
    rainChance: 65,
    uvIndex: 5,
    airQuality: { aqi: 19, status: 'Good' },
    todaySummary: 'Serene ridge-top climate with refreshing cool breezes, valley fog in mornings, and pleasant afternoon showers.',
    metrics: [
      { label: 'Humidity', value: '87%', detail: 'High humidity', icon: 'humidity' },
      { label: 'Wind speed', value: '10 km/h', detail: 'Gentle ridge draft', icon: 'wind' },
      { label: 'Barometer', value: '1011 hPa', detail: 'Stable', icon: 'pressure' },
      { label: 'Visibility', value: '6.5 km', detail: 'Valley fog', icon: 'visibility' },
      { label: 'UV Index', value: '5 of 11', detail: 'Moderate', icon: 'thermometer' },
      { label: 'Rain chance', value: '65%', detail: 'Intermittent rain', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 26, low: 18, rainChance: 65, rainfall: 11.0, condition: 'Passing Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 25, low: 17, rainChance: 70, rainfall: 15.0, condition: 'Hill Rain' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 27, low: 18, rainChance: 40, rainfall: 4.0, condition: 'Scattered Sun' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 28, low: 18, rainChance: 20, rainfall: 0.0, condition: 'Clear Sky' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 27, low: 19, rainChance: 30, rainfall: 2.0, condition: 'Pleasant Breeze' },
    ],
  },
  {
    id: 'nagaland',
    name: 'Nagaland',
    hindiName: 'नागालैंड',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Kohima / Dimapur',
    type: 'State',
    region: 'North-East',
    lat: 25.6751,
    lng: 94.1086,
    temperature: 22,
    feelsLike: 22,
    high: 25,
    low: 16,
    condition: 'Cool Hills & Light Showers',
    icon: 'rain',
    humidity: 85,
    windSpeed: 11,
    windDirection: 'NE',
    pressure: 1012,
    visibility: 7.0,
    rainChance: 60,
    uvIndex: 6,
    airQuality: { aqi: 21, status: 'Good' },
    todaySummary: 'Crisp Naga hills atmosphere with cool winds along high ridges and sporadic rain in foothills.',
    metrics: [
      { label: 'Humidity', value: '85%', detail: 'Clean hill air', icon: 'humidity' },
      { label: 'Wind speed', value: '11 km/h', detail: 'Northeasterly', icon: 'wind' },
      { label: 'Barometer', value: '1012 hPa', detail: 'High', icon: 'pressure' },
      { label: 'Visibility', value: '7.0 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '6 of 11', detail: 'Moderate', icon: 'thermometer' },
      { label: 'Rain chance', value: '60%', detail: 'Hill drizzle', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 25, low: 16, rainChance: 60, rainfall: 8.5, condition: 'Light Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 24, low: 15, rainChance: 65, rainfall: 12.0, condition: 'Rain Spells' },
      { day: 'Fri', date: '12 Sep', icon: 'cloudy', high: 25, low: 16, rainChance: 35, rainfall: 2.5, condition: 'Overcast Ridge' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 27, low: 17, rainChance: 15, rainfall: 0.0, condition: 'Sunny & Crisp' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 26, low: 16, rainChance: 25, rainfall: 1.0, condition: 'Partly Sunny' },
    ],
  },
  {
    id: 'odisha',
    name: 'Odisha',
    hindiName: 'ओडिशा',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Bhubaneswar / Cuttack',
    type: 'State',
    region: 'East',
    lat: 20.2961,
    lng: 85.8245,
    temperature: 31,
    feelsLike: 37,
    high: 33,
    low: 25,
    condition: 'Cyclonic Circulation / Coastal Gusts',
    icon: 'windy',
    humidity: 86,
    windSpeed: 28,
    windDirection: 'ENE',
    pressure: 1004,
    visibility: 6.5,
    rainChance: 75,
    uvIndex: 7,
    airQuality: { aqi: 52, status: 'Moderate' },
    alert: {
      severity: 'high',
      title: 'Bay of Bengal Depression Alert',
      description: 'Squally surface winds up to 45 km/h along Puri and Paradip. Fishermen warned against deep sea venture.',
    },
    todaySummary: 'Active low-pressure system in northern Bay of Bengal driving strong gusty winds and widespread coastal rainfall.',
    metrics: [
      { label: 'Humidity', value: '86%', detail: 'High marine influx', icon: 'humidity' },
      { label: 'Wind speed', value: '28 km/h', detail: 'Cyclonic gust ENE', icon: 'wind' },
      { label: 'Barometer', value: '1004 hPa', detail: 'Active depression', icon: 'pressure' },
      { label: 'Visibility', value: '6.5 km', detail: 'Reduced by rain spray', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '75%', detail: 'Heavy coastal bands', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'windy', high: 33, low: 25, rainChance: 75, rainfall: 28.0, condition: 'Gusty Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 31, low: 24, rainChance: 85, rainfall: 38.0, condition: 'Heavy Downpour' },
      { day: 'Fri', date: '12 Sep', icon: 'thunderstorm', high: 30, low: 24, rainChance: 70, rainfall: 20.0, condition: 'Squalls' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 32, low: 25, rainChance: 40, rainfall: 5.0, condition: 'Improving' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 34, low: 26, rainChance: 20, rainfall: 0.0, condition: 'Sunny & Warm' },
    ],
  },
  {
    id: 'punjab',
    name: 'Punjab',
    hindiName: 'पंजाब',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Chandigarh / Amritsar',
    type: 'State',
    region: 'North',
    lat: 31.1471,
    lng: 75.3412,
    temperature: 33,
    feelsLike: 35,
    high: 36,
    low: 24,
    condition: 'Sunny & Clear Skies',
    icon: 'sunny',
    humidity: 50,
    windSpeed: 12,
    windDirection: 'NW',
    pressure: 1010,
    visibility: 9.0,
    rainChance: 10,
    uvIndex: 8,
    airQuality: { aqi: 110, status: 'Moderate' },
    todaySummary: 'Dry sunshine across the five rivers. Ideal weather for paddy development and agricultural operations.',
    metrics: [
      { label: 'Humidity', value: '50%', detail: 'Comfortably dry', icon: 'humidity' },
      { label: 'Wind speed', value: '12 km/h', detail: 'Gentle NW wind', icon: 'wind' },
      { label: 'Barometer', value: '1010 hPa', detail: 'High stability', icon: 'pressure' },
      { label: 'Visibility', value: '9.0 km', detail: 'Good visibility', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '10%', detail: 'Minimal rain risk', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'sunny', high: 36, low: 24, rainChance: 10, rainfall: 0.0, condition: 'Clear Sunshine' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 37, low: 25, rainChance: 10, rainfall: 0.0, condition: 'Sunny Day' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 35, low: 24, rainChance: 25, rainfall: 1.5, condition: 'Passing Clouds' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 36, low: 25, rainChance: 15, rainfall: 0.0, condition: 'Dry & Warm' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 37, low: 25, rainChance: 10, rainfall: 0.0, condition: 'Clear Sky' },
    ],
  },
  {
    id: 'rajasthan',
    name: 'Rajasthan',
    hindiName: 'राजस्थान',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Jaipur / Jodhpur',
    type: 'State',
    region: 'North',
    lat: 26.9124,
    lng: 75.7873,
    temperature: 36,
    feelsLike: 38,
    high: 38,
    low: 26,
    condition: 'Bright Desert Sun',
    icon: 'sunny',
    humidity: 42,
    windSpeed: 16,
    windDirection: 'WNW',
    pressure: 1007,
    visibility: 9.5,
    rainChance: 5,
    uvIndex: 10,
    airQuality: { aqi: 120, status: 'Moderate' },
    alert: {
      severity: 'information',
      title: 'High Afternoon UV Index Warning',
      description: 'Peak daytime UV exceeding 10. Protective measures recommended between 12:00 and 15:30.',
    },
    todaySummary: 'Arid warmth with intense sunshine across Thar desert and eastern Aravalli districts.',
    metrics: [
      { label: 'Humidity', value: '42%', detail: 'Low dry air', icon: 'humidity' },
      { label: 'Wind speed', value: '16 km/h', detail: 'Warm westerly', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Thermal trough', icon: 'pressure' },
      { label: 'Visibility', value: '9.5 km', detail: 'Clear desert sight', icon: 'visibility' },
      { label: 'UV Index', value: '10 of 11', detail: 'Extreme midday', icon: 'thermometer' },
      { label: 'Rain chance', value: '5%', detail: 'Dry conditions', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'sunny', high: 38, low: 26, rainChance: 5, rainfall: 0.0, condition: 'Bright Sun' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 39, low: 27, rainChance: 5, rainfall: 0.0, condition: 'Hot & Clear' },
      { day: 'Fri', date: '12 Sep', icon: 'sunny', high: 38, low: 26, rainChance: 10, rainfall: 0.0, condition: 'Sunny' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 37, low: 25, rainChance: 15, rainfall: 0.5, condition: 'Passing Cloud' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 38, low: 26, rainChance: 10, rainfall: 0.0, condition: 'Sunny Sky' },
    ],
  },
  {
    id: 'sikkim',
    name: 'Sikkim',
    hindiName: 'सिक्किम',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Gangtok',
    type: 'State',
    region: 'North-East',
    lat: 27.3389,
    lng: 88.6065,
    temperature: 18,
    feelsLike: 18,
    high: 21,
    low: 13,
    condition: 'Himalayan Mist & Mountain Rain',
    icon: 'rain',
    humidity: 89,
    windSpeed: 8,
    windDirection: 'N',
    pressure: 1015,
    visibility: 5.5,
    rainChance: 70,
    uvIndex: 5,
    airQuality: { aqi: 15, status: 'Good' },
    todaySummary: 'Picturesque alpine weather with cool mountain breeze and intermittent cloudbursts along Teesta basin.',
    metrics: [
      { label: 'Humidity', value: '89%', detail: 'Alpine saturation', icon: 'humidity' },
      { label: 'Wind speed', value: '8 km/h', detail: 'Gentle valley draft', icon: 'wind' },
      { label: 'Barometer', value: '1015 hPa', detail: 'Alpine high', icon: 'pressure' },
      { label: 'Visibility', value: '5.5 km', detail: 'Mountain mist', icon: 'visibility' },
      { label: 'UV Index', value: '5 of 11', detail: 'Moderate', icon: 'thermometer' },
      { label: 'Rain chance', value: '70%', detail: 'Frequent showers', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 21, low: 13, rainChance: 70, rainfall: 14.0, condition: 'Mountain Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 20, low: 12, rainChance: 75, rainfall: 18.0, condition: 'Rain Spells' },
      { day: 'Fri', date: '12 Sep', icon: 'cloudy', high: 21, low: 13, rainChance: 45, rainfall: 5.0, condition: 'Overcast Peaks' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 22, low: 14, rainChance: 30, rainfall: 2.0, condition: 'Sunny Breaks' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 23, low: 14, rainChance: 15, rainfall: 0.0, condition: 'Clear Peaks' },
    ],
  },
  {
    id: 'tamil-nadu',
    name: 'Tamil Nadu',
    hindiName: 'तमिलनाडु',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Chennai / Coimbatore',
    type: 'State',
    region: 'South',
    lat: 13.0827,
    lng: 80.2707,
    temperature: 33,
    feelsLike: 39,
    high: 35,
    low: 27,
    condition: 'Sunny & Warm Coastal Weather',
    icon: 'sunny',
    humidity: 75,
    windSpeed: 15,
    windDirection: 'SE',
    pressure: 1008,
    visibility: 8.5,
    rainChance: 20,
    uvIndex: 9,
    airQuality: { aqi: 64, status: 'Moderate' },
    todaySummary: 'Warm coastal weather with bright sunshine throughout the day and gentle afternoon Coromandel breeze.',
    metrics: [
      { label: 'Humidity', value: '75%', detail: 'Coastal moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '15 km/h', detail: 'SE sea breeze', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Stable', icon: 'pressure' },
      { label: 'Visibility', value: '8.5 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '9 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '20%', detail: 'Isolated evening', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'sunny', high: 35, low: 27, rainChance: 20, rainfall: 1.2, condition: 'Sunny & Warm' },
      { day: 'Thu', date: '11 Sep', icon: 'partly-cloudy', high: 34, low: 26, rainChance: 30, rainfall: 2.5, condition: 'Passing Clouds' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 33, low: 25, rainChance: 50, rainfall: 8.0, condition: 'Evening Showers' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 34, low: 26, rainChance: 20, rainfall: 0.5, condition: 'Warm & Sunny' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 36, low: 27, rainChance: 15, rainfall: 0.0, condition: 'Clear Sky' },
    ],
  },
  {
    id: 'telangana',
    name: 'Telangana',
    hindiName: 'तेलंगाना',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Hyderabad',
    type: 'State',
    region: 'South',
    lat: 17.385,
    lng: 78.4867,
    temperature: 29,
    feelsLike: 32,
    high: 31,
    low: 22,
    condition: 'Partly Cloudy & Pleasant',
    icon: 'partly-cloudy',
    humidity: 65,
    windSpeed: 14,
    windDirection: 'W',
    pressure: 1010,
    visibility: 8.5,
    rainChance: 30,
    uvIndex: 7,
    airQuality: { aqi: 70, status: 'Moderate' },
    todaySummary: 'Deccan plateau weather with pleasant afternoon winds and mild evening temperatures across Hyderabad.',
    metrics: [
      { label: 'Humidity', value: '65%', detail: 'Comfortable', icon: 'humidity' },
      { label: 'Wind speed', value: '14 km/h', detail: 'Westerly breeze', icon: 'wind' },
      { label: 'Barometer', value: '1010 hPa', detail: 'Normal', icon: 'pressure' },
      { label: 'Visibility', value: '8.5 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '30%', detail: 'Scattered drizzle', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 31, low: 22, rainChance: 30, rainfall: 2.0, condition: 'Partly Cloudy' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 30, low: 22, rainChance: 45, rainfall: 6.0, condition: 'Scattered Showers' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 29, low: 21, rainChance: 55, rainfall: 9.5, condition: 'Light Rain' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 31, low: 22, rainChance: 25, rainfall: 1.0, condition: 'Pleasant Sun' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 32, low: 23, rainChance: 15, rainfall: 0.0, condition: 'Bright & Warm' },
    ],
  },
  {
    id: 'tripura',
    name: 'Tripura',
    hindiName: 'त्रिपुरा',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Agartala',
    type: 'State',
    region: 'North-East',
    lat: 23.8315,
    lng: 91.2868,
    temperature: 30,
    feelsLike: 35,
    high: 32,
    low: 24,
    condition: 'Warm & Tropical Showers',
    icon: 'rain',
    humidity: 86,
    windSpeed: 11,
    windDirection: 'S',
    pressure: 1007,
    visibility: 7.0,
    rainChance: 65,
    uvIndex: 7,
    airQuality: { aqi: 34, status: 'Good' },
    todaySummary: 'Humid tropical plains with good rainfall distribution across rubber plantations and paddy fields.',
    metrics: [
      { label: 'Humidity', value: '86%', detail: 'Tropical humidity', icon: 'humidity' },
      { label: 'Wind speed', value: '11 km/h', detail: 'Southerly breeze', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Low', icon: 'pressure' },
      { label: 'Visibility', value: '7.0 km', detail: 'Moderate', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '65%', detail: 'Afternoon rain', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 32, low: 24, rainChance: 65, rainfall: 14.0, condition: 'Tropical Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 31, low: 23, rainChance: 70, rainfall: 19.0, condition: 'Monsoon Rain' },
      { day: 'Fri', date: '12 Sep', icon: 'thunderstorm', high: 30, low: 23, rainChance: 60, rainfall: 15.0, condition: 'Thunderstorm' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 32, low: 24, rainChance: 35, rainfall: 3.5, condition: 'Breaks in Cloud' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 33, low: 25, rainChance: 20, rainfall: 0.0, condition: 'Sunny Day' },
    ],
  },
  {
    id: 'uttar-pradesh',
    name: 'Uttar Pradesh',
    hindiName: 'उत्तर प्रदेश',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Lucknow / Varanasi',
    type: 'State',
    region: 'North',
    lat: 26.8467,
    lng: 80.9462,
    temperature: 32,
    feelsLike: 36,
    high: 35,
    low: 25,
    condition: 'Partly Cloudy & Warm',
    icon: 'partly-cloudy',
    humidity: 68,
    windSpeed: 13,
    windDirection: 'ESE',
    pressure: 1008,
    visibility: 7.5,
    rainChance: 30,
    uvIndex: 8,
    airQuality: { aqi: 125, status: 'Moderate' },
    todaySummary: 'Vast Gangetic heartland seeing warm sunshine with scattered clouds and isolated localized showers.',
    metrics: [
      { label: 'Humidity', value: '68%', detail: 'Moderate Gangetic', icon: 'humidity' },
      { label: 'Wind speed', value: '13 km/h', detail: 'ESE breeze', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Steady', icon: 'pressure' },
      { label: 'Visibility', value: '7.5 km', detail: 'Moderate haze', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '30%', detail: 'Isolated thunder', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 35, low: 25, rainChance: 30, rainfall: 2.2, condition: 'Partly Cloudy' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 34, low: 24, rainChance: 45, rainfall: 6.0, condition: 'Scattered Showers' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 32, low: 24, rainChance: 60, rainfall: 14.0, condition: 'Monsoon Rain' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 35, low: 25, rainChance: 20, rainfall: 0.0, condition: 'Sunny Horizons' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 36, low: 26, rainChance: 15, rainfall: 0.0, condition: 'Clear Sky' },
    ],
  },
  {
    id: 'uttarakhand',
    name: 'Uttarakhand',
    hindiName: 'उत्तराखंड',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Dehradun / Gairsain',
    type: 'State',
    region: 'North',
    lat: 30.3165,
    lng: 78.0322,
    temperature: 24,
    feelsLike: 25,
    high: 27,
    low: 18,
    condition: 'Foothill Rain & Clear Ridges',
    icon: 'rain',
    humidity: 78,
    windSpeed: 10,
    windDirection: 'NE',
    pressure: 1012,
    visibility: 8.5,
    rainChance: 50,
    uvIndex: 7,
    airQuality: { aqi: 35, status: 'Good' },
    todaySummary: 'Fresh mountain breezes with clean air, afternoon showers across Shivalik ranges and pleasant high valleys.',
    metrics: [
      { label: 'Humidity', value: '78%', detail: 'Pleasant mountain air', icon: 'humidity' },
      { label: 'Wind speed', value: '10 km/h', detail: 'Northeasterly', icon: 'wind' },
      { label: 'Barometer', value: '1012 hPa', detail: 'High', icon: 'pressure' },
      { label: 'Visibility', value: '8.5 km', detail: 'Very clear', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '50%', detail: 'Passing hill rain', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 27, low: 18, rainChance: 50, rainfall: 8.0, condition: 'Foothill Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 26, low: 17, rainChance: 60, rainfall: 12.0, condition: 'Showers' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 28, low: 18, rainChance: 30, rainfall: 2.0, condition: 'Partly Sunny' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 29, low: 19, rainChance: 15, rainfall: 0.0, condition: 'Sunny Mountain' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 29, low: 19, rainChance: 10, rainfall: 0.0, condition: 'Clear Skies' },
    ],
  },
  {
    id: 'west-bengal',
    name: 'West Bengal',
    hindiName: 'पश्चिम बंगाल',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Kolkata',
    type: 'State',
    region: 'East',
    lat: 22.5726,
    lng: 88.3639,
    temperature: 31,
    feelsLike: 37,
    high: 33,
    low: 26,
    condition: 'Humid & Overcast Spells',
    icon: 'cloudy',
    humidity: 82,
    windSpeed: 14,
    windDirection: 'S',
    pressure: 1006,
    visibility: 7.0,
    rainChance: 60,
    uvIndex: 7,
    airQuality: { aqi: 82, status: 'Moderate' },
    todaySummary: 'Deltaic warmth with high atmospheric moisture, overcast skies, and passing coastal showers.',
    metrics: [
      { label: 'Humidity', value: '82%', detail: 'High delta moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '14 km/h', detail: 'Southerly breeze', icon: 'wind' },
      { label: 'Barometer', value: '1006 hPa', detail: 'Coastal low', icon: 'pressure' },
      { label: 'Visibility', value: '7.0 km', detail: 'Haze', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '60%', detail: 'Passing rain bands', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'cloudy', high: 33, low: 26, rainChance: 60, rainfall: 10.0, condition: 'Overcast & Rain' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 32, low: 25, rainChance: 70, rainfall: 16.0, condition: 'Monsoon Showers' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 31, low: 25, rainChance: 75, rainfall: 20.0, condition: 'Wet Spells' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 33, low: 26, rainChance: 40, rainfall: 4.0, condition: 'Partly Sunny' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 34, low: 26, rainChance: 25, rainfall: 1.0, condition: 'Warm Breeze' },
    ],
  },

  // --- 8 UNION TERRITORIES OF INDIA ---
  {
    id: 'delhi',
    name: 'Delhi (NCT)',
    hindiName: 'दिल्ली (रा.रा.क्षे.)',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'New Delhi',
    type: 'Union Territory',
    region: 'North',
    lat: 28.6139,
    lng: 77.209,
    temperature: 32,
    feelsLike: 35,
    high: 34,
    low: 25,
    condition: 'Partly Cloudy & Warm',
    icon: 'partly-cloudy',
    humidity: 65,
    windSpeed: 14,
    windDirection: 'WNW',
    pressure: 1008,
    visibility: 7.5,
    rainChance: 25,
    uvIndex: 8,
    airQuality: { aqi: 142, status: 'Moderate' },
    todaySummary: 'National Capital Territory seeing warm seasonal conditions with gentle northwesterly breeze and steady barometer.',
    metrics: [
      { label: 'Humidity', value: '65%', detail: 'Moderate feel', icon: 'humidity' },
      { label: 'Wind speed', value: '14 km/h', detail: 'WNW breeze', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Steady', icon: 'pressure' },
      { label: 'Visibility', value: '7.5 km', detail: 'Moderate haze', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'High', icon: 'thermometer' },
      { label: 'Rain chance', value: '25%', detail: 'Passing cloud', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 34, low: 25, rainChance: 25, rainfall: 1.5, condition: 'Partly Cloudy' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 35, low: 26, rainChance: 15, rainfall: 0.0, condition: 'Sunny & Clear' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 33, low: 24, rainChance: 45, rainfall: 6.0, condition: 'Scattered Rain' },
      { day: 'Sat', date: '13 Sep', icon: 'partly-cloudy', high: 34, low: 25, rainChance: 20, rainfall: 0.5, condition: 'Partly Sunny' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 35, low: 25, rainChance: 10, rainfall: 0.0, condition: 'Clear Sky' },
    ],
  },
  {
    id: 'jammu-kashmir',
    name: 'Jammu & Kashmir',
    hindiName: 'जम्मू और कश्मीर',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Srinagar (Summer) / Jammu (Winter)',
    type: 'Union Territory',
    region: 'North',
    lat: 34.0837,
    lng: 74.7973,
    temperature: 21,
    feelsLike: 21,
    high: 24,
    low: 12,
    condition: 'Crisp Valley Sunshine',
    icon: 'sunny',
    humidity: 52,
    windSpeed: 9,
    windDirection: 'N',
    pressure: 1016,
    visibility: 10.0,
    rainChance: 15,
    uvIndex: 7,
    airQuality: { aqi: 24, status: 'Good' },
    todaySummary: 'Pristine Kashmir valley skies with golden sunshine over Dal Lake and crisp mountain winds.',
    metrics: [
      { label: 'Humidity', value: '52%', detail: 'Crisp & clean', icon: 'humidity' },
      { label: 'Wind speed', value: '9 km/h', detail: 'Gentle valley draft', icon: 'wind' },
      { label: 'Barometer', value: '1016 hPa', detail: 'High pressure', icon: 'pressure' },
      { label: 'Visibility', value: '10.0 km', detail: 'Exceptional clarity', icon: 'visibility' },
      { label: 'UV Index', value: '7 of 11', detail: 'High mountain sun', icon: 'thermometer' },
      { label: 'Rain chance', value: '15%', detail: 'Clear conditions', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'sunny', high: 24, low: 12, rainChance: 15, rainfall: 0.0, condition: 'Clear Valley' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 25, low: 13, rainChance: 10, rainfall: 0.0, condition: 'Sunny Horizons' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 23, low: 12, rainChance: 25, rainfall: 1.0, condition: 'Passing Cloud' },
      { day: 'Sat', date: '13 Sep', icon: 'rain', high: 21, low: 11, rainChance: 45, rainfall: 5.0, condition: 'Light Rain' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 23, low: 11, rainChance: 10, rainfall: 0.0, condition: 'Pristine Sun' },
    ],
  },
  {
    id: 'ladakh',
    name: 'Ladakh',
    hindiName: 'लद्दाख',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Leh',
    type: 'Union Territory',
    region: 'North',
    lat: 34.1526,
    lng: 77.5771,
    temperature: 14,
    feelsLike: 12,
    high: 17,
    low: 4,
    condition: 'High Altitude Sun & Cold Nights',
    icon: 'sunny',
    humidity: 28,
    windSpeed: 20,
    windDirection: 'NNW',
    pressure: 1018,
    visibility: 12.0,
    rainChance: 0,
    uvIndex: 11,
    airQuality: { aqi: 12, status: 'Good' },
    alert: {
      severity: 'information',
      title: 'High Altitude Cold & Extreme UV',
      description: 'UV Index exceeding 11; sub-zero overnight temperatures in Khardung La and Chang La passes.',
    },
    todaySummary: 'Cold desert plateau with dazzling azure skies, razor-sharp visibility, and chilly evening descent.',
    metrics: [
      { label: 'Humidity', value: '28%', detail: 'Cold dry desert', icon: 'humidity' },
      { label: 'Wind speed', value: '20 km/h', detail: 'High pass wind', icon: 'wind' },
      { label: 'Barometer', value: '1018 hPa', detail: 'High alpine', icon: 'pressure' },
      { label: 'Visibility', value: '12.0 km', detail: 'Infinite clarity', icon: 'visibility' },
      { label: 'UV Index', value: '11 of 11', detail: 'Extreme alpine', icon: 'thermometer' },
      { label: 'Rain chance', value: '0%', detail: 'Zero rain risk', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'sunny', high: 17, low: 4, rainChance: 0, rainfall: 0.0, condition: 'Pure Sun' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 18, low: 5, rainChance: 0, rainfall: 0.0, condition: 'Azure Sky' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 16, low: 3, rainChance: 10, rainfall: 0.0, condition: 'High Cirrus' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 17, low: 4, rainChance: 5, rainfall: 0.0, condition: 'Sunny & Cold' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 16, low: 3, rainChance: 0, rainfall: 0.0, condition: 'Cold Desert' },
    ],
  },
  {
    id: 'andaman-nicobar',
    name: 'Andaman & Nicobar Islands',
    hindiName: 'अंडमान और निकोबार द्वीप समूह',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Port Blair',
    type: 'Union Territory',
    region: 'Islands',
    lat: 11.6234,
    lng: 92.7265,
    temperature: 29,
    feelsLike: 34,
    high: 31,
    low: 25,
    condition: 'Maritime Breeze & Island Showers',
    icon: 'rain',
    humidity: 84,
    windSpeed: 25,
    windDirection: 'SW',
    pressure: 1007,
    visibility: 8.0,
    rainChance: 65,
    uvIndex: 8,
    airQuality: { aqi: 18, status: 'Good' },
    todaySummary: 'Vibrant oceanic islands with turquoise waters, fresh maritime gusts, and passing tropical showers.',
    metrics: [
      { label: 'Humidity', value: '84%', detail: 'Oceanic moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '25 km/h', detail: 'SW trade wind', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Maritime trough', icon: 'pressure' },
      { label: 'Visibility', value: '8.0 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '65%', detail: 'Island downpours', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 31, low: 25, rainChance: 65, rainfall: 15.0, condition: 'Island Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 30, low: 24, rainChance: 70, rainfall: 22.0, condition: 'Tropical Rain' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 31, low: 25, rainChance: 40, rainfall: 4.0, condition: 'Breezy Sun' },
      { day: 'Sat', date: '13 Sep', icon: 'rain', high: 30, low: 25, rainChance: 60, rainfall: 12.0, condition: 'Passing Squall' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 32, low: 26, rainChance: 35, rainfall: 3.0, condition: 'Sunny Intervals' },
    ],
  },
  {
    id: 'chandigarh',
    name: 'Chandigarh',
    hindiName: 'चंडीगढ़',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Chandigarh',
    type: 'Union Territory',
    region: 'North',
    lat: 30.7333,
    lng: 76.7794,
    temperature: 32,
    feelsLike: 35,
    high: 35,
    low: 24,
    condition: 'Pleasant & Partly Sunny',
    icon: 'partly-cloudy',
    humidity: 55,
    windSpeed: 12,
    windDirection: 'NW',
    pressure: 1010,
    visibility: 9.0,
    rainChance: 15,
    uvIndex: 8,
    airQuality: { aqi: 82, status: 'Moderate' },
    todaySummary: 'The Beautiful City enjoying clear skies, gentle Shivalik breezes, and comfortable late summer temperatures.',
    metrics: [
      { label: 'Humidity', value: '55%', detail: 'Moderate', icon: 'humidity' },
      { label: 'Wind speed', value: '12 km/h', detail: 'Northwesterly', icon: 'wind' },
      { label: 'Barometer', value: '1010 hPa', detail: 'Steady', icon: 'pressure' },
      { label: 'Visibility', value: '9.0 km', detail: 'Clear', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '15%', detail: 'Low risk', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 35, low: 24, rainChance: 15, rainfall: 0.5, condition: 'Partly Sunny' },
      { day: 'Thu', date: '11 Sep', icon: 'sunny', high: 36, low: 25, rainChance: 10, rainfall: 0.0, condition: 'Sunny' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 33, low: 23, rainChance: 40, rainfall: 4.0, condition: 'Passing Shower' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 35, low: 24, rainChance: 15, rainfall: 0.0, condition: 'Clear Sky' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 36, low: 25, rainChance: 10, rainfall: 0.0, condition: 'Bright Day' },
    ],
  },
  {
    id: 'dadra-nagar-haveli-daman-diu',
    name: 'Dadra & Nagar Haveli and Daman & Diu',
    hindiName: 'दादरा और नगर हवेली एवं दमन और दीव',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Daman',
    type: 'Union Territory',
    region: 'West',
    lat: 20.4283,
    lng: 72.8397,
    temperature: 31,
    feelsLike: 36,
    high: 33,
    low: 26,
    condition: 'Coastal Warmth & Breezes',
    icon: 'partly-cloudy',
    humidity: 78,
    windSpeed: 21,
    windDirection: 'SW',
    pressure: 1007,
    visibility: 8.0,
    rainChance: 35,
    uvIndex: 8,
    airQuality: { aqi: 56, status: 'Moderate' },
    todaySummary: 'Gulf of Khambhat coastline experiencing warm sunshine and bracing sea breezes with light passing showers.',
    metrics: [
      { label: 'Humidity', value: '78%', detail: 'Coastal moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '21 km/h', detail: 'SW sea wind', icon: 'wind' },
      { label: 'Barometer', value: '1007 hPa', detail: 'Normal', icon: 'pressure' },
      { label: 'Visibility', value: '8.0 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '8 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '35%', detail: 'Passing drizzle', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'partly-cloudy', high: 33, low: 26, rainChance: 35, rainfall: 3.0, condition: 'Breezy & Sun' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 32, low: 25, rainChance: 50, rainfall: 7.0, condition: 'Coastal Shower' },
      { day: 'Fri', date: '12 Sep', icon: 'sunny', high: 34, low: 26, rainChance: 20, rainfall: 0.5, condition: 'Sunny Horizons' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 34, low: 26, rainChance: 15, rainfall: 0.0, condition: 'Clear Skies' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 33, low: 26, rainChance: 25, rainfall: 1.0, condition: 'Sea Breeze' },
    ],
  },
  {
    id: 'lakshadweep',
    name: 'Lakshadweep',
    hindiName: 'लक्षद्वीप',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Kavaratti',
    type: 'Union Territory',
    region: 'Islands',
    lat: 10.5667,
    lng: 72.6417,
    temperature: 29,
    feelsLike: 34,
    high: 31,
    low: 26,
    condition: 'Coral Atoll Breezes & Showers',
    icon: 'rain',
    humidity: 82,
    windSpeed: 23,
    windDirection: 'WSW',
    pressure: 1008,
    visibility: 8.5,
    rainChance: 60,
    uvIndex: 9,
    airQuality: { aqi: 14, status: 'Good' },
    todaySummary: 'Pristine coral archipelago with azure lagoons, steady southwesterly breeze, and scattered tropical showers.',
    metrics: [
      { label: 'Humidity', value: '82%', detail: 'Atoll humidity', icon: 'humidity' },
      { label: 'Wind speed', value: '23 km/h', detail: 'WSW oceanic wind', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Stable', icon: 'pressure' },
      { label: 'Visibility', value: '8.5 km', detail: 'Excellent', icon: 'visibility' },
      { label: 'UV Index', value: '9 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '60%', detail: 'Passing squalls', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'rain', high: 31, low: 26, rainChance: 60, rainfall: 11.0, condition: 'Lagoon Showers' },
      { day: 'Thu', date: '11 Sep', icon: 'rain', high: 30, low: 25, rainChance: 65, rainfall: 16.0, condition: 'Tropical Rain' },
      { day: 'Fri', date: '12 Sep', icon: 'partly-cloudy', high: 31, low: 26, rainChance: 35, rainfall: 3.0, condition: 'Breezy Sun' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 32, low: 26, rainChance: 20, rainfall: 0.0, condition: 'Sunny Reef' },
      { day: 'Sun', date: '14 Sep', icon: 'partly-cloudy', high: 32, low: 27, rainChance: 25, rainfall: 1.5, condition: 'Calm Waters' },
    ],
  },
  {
    id: 'puducherry',
    name: 'Puducherry',
    hindiName: 'पुडुचेरी',
    country: 'India',
    countryHindi: 'भारत',
    capital: 'Puducherry',
    type: 'Union Territory',
    region: 'South',
    lat: 11.9416,
    lng: 79.8083,
    temperature: 32,
    feelsLike: 37,
    high: 34,
    low: 26,
    condition: 'Sunny Coastal Promenade',
    icon: 'sunny',
    humidity: 76,
    windSpeed: 17,
    windDirection: 'SE',
    pressure: 1008,
    visibility: 8.5,
    rainChance: 25,
    uvIndex: 9,
    airQuality: { aqi: 42, status: 'Good' },
    todaySummary: 'French colonial promenade enjoying warm sunny skies, pleasant Coromandel waves, and gentle sea breezes.',
    metrics: [
      { label: 'Humidity', value: '76%', detail: 'Coastal moisture', icon: 'humidity' },
      { label: 'Wind speed', value: '17 km/h', detail: 'SE sea breeze', icon: 'wind' },
      { label: 'Barometer', value: '1008 hPa', detail: 'Normal', icon: 'pressure' },
      { label: 'Visibility', value: '8.5 km', detail: 'Good', icon: 'visibility' },
      { label: 'UV Index', value: '9 of 11', detail: 'Very High', icon: 'thermometer' },
      { label: 'Rain chance', value: '25%', detail: 'Isolated drizzle', icon: 'humidity' },
    ],
    forecast: [
      { day: 'Today', date: '10 Sep', icon: 'sunny', high: 34, low: 26, rainChance: 25, rainfall: 1.5, condition: 'Sunny Promenade' },
      { day: 'Thu', date: '11 Sep', icon: 'partly-cloudy', high: 34, low: 26, rainChance: 30, rainfall: 2.0, condition: 'Passing Clouds' },
      { day: 'Fri', date: '12 Sep', icon: 'rain', high: 32, low: 25, rainChance: 50, rainfall: 7.0, condition: 'Evening Showers' },
      { day: 'Sat', date: '13 Sep', icon: 'sunny', high: 34, low: 26, rainChance: 20, rainfall: 0.5, condition: 'Warm & Sunny' },
      { day: 'Sun', date: '14 Sep', icon: 'sunny', high: 35, low: 27, rainChance: 15, rainfall: 0.0, condition: 'Clear Sky' },
    ],
  },
];

export const TOTAL_STATES_COUNT = ALL_INDIAN_STATES_WEATHER.filter((item) => item.type === 'State').length;
export const TOTAL_UTS_COUNT = ALL_INDIAN_STATES_WEATHER.filter((item) => item.type === 'Union Territory').length;
export const TOTAL_ADMIN_DIVISIONS_COUNT = ALL_INDIAN_STATES_WEATHER.length;
