export interface IndianStateInfo {
  id: string;
  name: string;
  hindiName: string;
  country: string;
  capital: string;
  region: string;
  temperature: number;
  feelsLike: number;
  condition: string;
  rainChance: number;
  humidity: number;
  windSpeed: number;
  aqi: number;
  alert?: string;
  advisory: {
    title: string;
    status: string;
    body: string;
    actions: string[];
  };
  keywords: string[];
}

export const INDIAN_STATES_DATA: IndianStateInfo[] = [
  {
    id: "andhra-pradesh",
    name: "Andhra Pradesh",
    hindiName: "आंध्र प्रदेश",
    country: "India",
    capital: "Amaravati",
    region: "South",
    temperature: 33,
    feelsLike: 38,
    condition: "Humid & Passing Showers",
    rainChance: 45,
    humidity: 78,
    windSpeed: 18,
    aqi: 68,
    alert: "Coastal swell & squall advisory for fishermen",
    advisory: {
      title: "Coastal Showers Advisory",
      status: "Moderate",
      body: "Light afternoon showers expected. Paddy and chili farmers should maintain drainage in coastal delta belts.",
      actions: ["Check coastal radar", "Manage paddy drainage", "View 5-day delta forecast"],
    },
    keywords: ["andhra", "andhra pradesh", "amaravati", "visakhapatnam", "vizag", "vijayawada", "आंध्र"],
  },
  {
    id: "arunachal-pradesh",
    name: "Arunachal Pradesh",
    hindiName: "अरुणाचल प्रदेश",
    country: "India",
    capital: "Itanagar",
    region: "North-East",
    temperature: 22,
    feelsLike: 23,
    condition: "Mountain Mist & Light Rain",
    rainChance: 65,
    humidity: 86,
    windSpeed: 10,
    aqi: 28,
    alert: "Slope and landslide watch on high-altitude roads",
    advisory: {
      title: "Mountain Highway Caution",
      status: "Caution",
      body: "Persistent rain along upper hill tracks. Travelers and fruit orchard growers advised to monitor highway passes.",
      actions: ["Check hill road pass alerts", "Orchard drainage tips", "Regional weather map"],
    },
    keywords: ["arunachal", "arunachal pradesh", "itanagar", "tawang", "pasighat", "अरुणाचल"],
  },
  {
    id: "assam",
    name: "Assam",
    hindiName: "असम",
    country: "India",
    capital: "Dispur",
    region: "North-East",
    temperature: 29,
    feelsLike: 34,
    condition: "Heavy Monsoon Showers",
    rainChance: 82,
    humidity: 88,
    windSpeed: 14,
    aqi: 42,
    alert: "Flood watch active along Brahmaputra basin",
    advisory: {
      title: "Flood Alert & Tea Garden Advisory",
      status: "Warning",
      body: "River levels rising across lower Assam. Tea estates should monitor soil runoff and suspend chemical sprays.",
      actions: ["IMD Brahmaputra bulletin", "Tea estate advisory", "Evacuation route maps"],
    },
    keywords: ["assam", "dispur", "guwahati", "dibrugarh", "silchar", "असम", "অসম"],
  },
  {
    id: "bihar",
    name: "Bihar",
    hindiName: "बिहार",
    country: "India",
    capital: "Patna",
    region: "East",
    temperature: 32,
    feelsLike: 37,
    condition: "Scattered Thunderstorms",
    rainChance: 55,
    humidity: 76,
    windSpeed: 16,
    aqi: 112,
    advisory: {
      title: "Thunderstorm Precaution",
      status: "Caution",
      body: "Afternoon convective showers likely in Gangetic plains. Farmers advised to take shelter during lightning.",
      actions: ["Damini lightning tracker", "Paddy field advisories", "3-day Gangetic outlook"],
    },
    keywords: ["bihar", "patna", "gaya", "muzaffarpur", "bhagalpur", "बिहार"],
  },
  {
    id: "chhattisgarh",
    name: "Chhattisgarh",
    hindiName: "छत्तीसगढ़",
    country: "India",
    capital: "Raipur",
    region: "Central",
    temperature: 30,
    feelsLike: 33,
    condition: "Overcast & Intermittent Rain",
    rainChance: 58,
    humidity: 74,
    windSpeed: 15,
    aqi: 62,
    advisory: {
      title: "Kharif Crop Rain Guidance",
      status: "Good",
      body: "Consistent moisture supports rice nurseries. Nitrogen top-dressing recommended once rain pauses.",
      actions: ["Rice crop advisory", "Raipur weather radar", "Soil moisture check"],
    },
    keywords: ["chhattisgarh", "raipur", "bilaspur", "durg", "bastar", "छत्तीसगढ़"],
  },
  {
    id: "goa",
    name: "Goa",
    hindiName: "गोवा",
    country: "India",
    capital: "Panaji",
    region: "West",
    temperature: 29,
    feelsLike: 33,
    condition: "Tropical Coastal Downpours",
    rainChance: 75,
    humidity: 84,
    windSpeed: 22,
    aqi: 35,
    alert: "Rough sea condition with 2.5m waves",
    advisory: {
      title: "Coastal Fishery Caution",
      status: "Caution",
      body: "High swell and gusty winds along Konkan-Goa coast. Sea ventures should remain suspended.",
      actions: ["Marine wave forecast", "Panaji beach warnings", "Fishermen hotline"],
    },
    keywords: ["goa", "panaji", "panjim", "margao", "vasco", "गोवा"],
  },
  {
    id: "gujarat",
    name: "Gujarat",
    hindiName: "गुजरात",
    country: "India",
    capital: "Gandhinagar",
    region: "West",
    temperature: 34,
    feelsLike: 38,
    condition: "Hot & Partly Cloudy",
    rainChance: 22,
    humidity: 62,
    windSpeed: 20,
    aqi: 88,
    advisory: {
      title: "Cotton & Groundnut Advisory",
      status: "Normal",
      body: "Favorable conditions for weed control and pesticide spray across Saurashtra and central Gujarat.",
      actions: ["Saurashtra weather", "Cotton pest management", "Irrigation schedule"],
    },
    keywords: ["gujarat", "gandhinagar", "ahmedabad", "surat", "vadodara", "rajkot", "ગુજરાત", "गुजरात"],
  },
  {
    id: "haryana",
    name: "Haryana",
    hindiName: "हरियाणा",
    country: "India",
    capital: "Chandigarh",
    region: "North",
    temperature: 33,
    feelsLike: 36,
    condition: "Warm & Sun with Clouds",
    rainChance: 20,
    humidity: 60,
    windSpeed: 14,
    aqi: 142,
    advisory: {
      title: "Air Quality & Crop Spray Guidance",
      status: "Notice",
      body: "Warm dry window through late evening. Suitable for farm operations; protect sensitive seedlings from heat.",
      actions: ["Check AQI forecast", "Spraying schedule", "Haryana agri bulletin"],
    },
    keywords: ["haryana", "gurugram", "faridabad", "hisar", "karnal", "हरियाणा"],
  },
  {
    id: "himachal-pradesh",
    name: "Himachal Pradesh",
    hindiName: "हिमाचल प्रदेश",
    country: "India",
    capital: "Shimla",
    region: "North",
    temperature: 21,
    feelsLike: 21,
    condition: "Breezy & Mountain Showers",
    rainChance: 60,
    humidity: 72,
    windSpeed: 12,
    aqi: 32,
    alert: "Localized fog and slippery roads in Kullu and Shimla",
    advisory: {
      title: "Apple Orchards & Hill Travel Notice",
      status: "Caution",
      body: "Showers favor apple sizing; however, check NH-05 and NH-21 highway status for rockfall alerts.",
      actions: ["Shimla hill pass status", "Apple harvest tips", "Touring weather report"],
    },
    keywords: ["himachal", "himachal pradesh", "shimla", "manali", "dharamshala", "kullu", "हिमाचल"],
  },
  {
    id: "jharkhand",
    name: "Jharkhand",
    hindiName: "झारखंड",
    country: "India",
    capital: "Ranchi",
    region: "East",
    temperature: 30,
    feelsLike: 34,
    condition: "Cloudy with Light Rain",
    rainChance: 48,
    humidity: 78,
    windSpeed: 13,
    aqi: 72,
    advisory: {
      title: "Plateau Agricultural Guidance",
      status: "Normal",
      body: "Moderate showers replenishing farm ponds across Chota Nagpur. Good time for pulses and oilseed sowing.",
      actions: ["Farm pond levels", "Sowing advisory", "Ranchi radar"],
    },
    keywords: ["jharkhand", "ranchi", "jamshedpur", "dhanbad", "bokaro", "झारखंड"],
  },
  {
    id: "karnataka",
    name: "Karnataka",
    hindiName: "कर्नाटक",
    country: "India",
    capital: "Bengaluru",
    region: "South",
    temperature: 28,
    feelsLike: 30,
    condition: "Pleasant Breezes & Drizzle",
    rainChance: 40,
    humidity: 68,
    windSpeed: 19,
    aqi: 45,
    advisory: {
      title: "Coffee & Urban Weather Update",
      status: "Good",
      body: "Pleasant temperatures in Bengaluru and plateau districts. Malnad coffee estates receive healthy periodic moisture.",
      actions: ["Bengaluru live radar", "Malnad coffee report", "Evening traffic forecast"],
    },
    keywords: ["karnataka", "bengaluru", "bangalore", "mysuru", "mysore", "hubballi", "mangalore", "ಕರ್ನಾಟಕ", "कर्नाटक"],
  },
  {
    id: "kerala",
    name: "Kerala",
    hindiName: "केरल",
    country: "India",
    capital: "Thiruvananthapuram",
    region: "South",
    temperature: 29,
    feelsLike: 34,
    condition: "Vigorous Monsoon Surge",
    rainChance: 85,
    humidity: 89,
    windSpeed: 21,
    aqi: 28,
    alert: "Heavy rainfall warning for central and north Kerala",
    advisory: {
      title: "Monsoon Surge & Plantation Caution",
      status: "Warning",
      body: "Heavy rain across Wayanad, Idukki, and Kozhikode. Cardamom and rubber estates should clear waterways.",
      actions: ["Kerala dam levels", "IMD yellow alert details", "Spice plantation advisory"],
    },
    keywords: ["kerala", "thiruvananthapuram", "kochi", "cochin", "kozhikode", "wayanad", "idukki", "കേരളം", "केरल"],
  },
  {
    id: "madhya-pradesh",
    name: "Madhya Pradesh",
    hindiName: "मध्य प्रदेश",
    country: "India",
    capital: "Bhopal",
    region: "Central",
    temperature: 31,
    feelsLike: 35,
    condition: "Scattered Rain & Sunshine",
    rainChance: 42,
    humidity: 70,
    windSpeed: 14,
    aqi: 74,
    advisory: {
      title: "Soybean & Pulse Crop Advisory",
      status: "Good",
      body: "Ideal moisture for soybean pod filling across Malwa and Nimar regions. Weed management can proceed on dry intervals.",
      actions: ["Malwa region weather", "Soybean health checklist", "Bhopal forecast"],
    },
    keywords: ["madhya pradesh", "mp", "bhopal", "indore", "gwalior", "jabalpur", "उज्जैन", "मध्य प्रदेश"],
  },
  {
    id: "maharashtra",
    name: "Maharashtra",
    hindiName: "महाराष्ट्र",
    country: "India",
    capital: "Mumbai",
    region: "West",
    temperature: 30,
    feelsLike: 35,
    condition: "Humid Showers & Gusts",
    rainChance: 68,
    humidity: 82,
    windSpeed: 23,
    aqi: 65,
    alert: "High tide alert of 4.2m along Mumbai coast",
    advisory: {
      title: "Mumbai Coastal Tide & Vidarbha Rain Notice",
      status: "Caution",
      body: "Avoid low-lying areas during coastal high tide. Marathwada and Vidarbha farmers should monitor soil moisture before spraying.",
      actions: ["Mumbai high tide timetable", "Cotton & sugarcane bulletin", "Local train weather watch"],
    },
    keywords: ["maharashtra", "mumbai", "pune", "nagpur", "nashik", "aurangabad", "छत्रपती संभाजीनगर", "महाराष्ट्र"],
  },
  {
    id: "manipur",
    name: "Manipur",
    hindiName: "मणिपुर",
    country: "India",
    capital: "Imphal",
    region: "North-East",
    temperature: 25,
    feelsLike: 27,
    condition: "Valley Rain & Overcast",
    rainChance: 62,
    humidity: 83,
    windSpeed: 11,
    aqi: 26,
    advisory: {
      title: "Valley Paddy Field Care",
      status: "Moderate",
      body: "Steady rains maintain optimal standing water for paddy in Imphal valley. Monitor bunds to prevent erosion.",
      actions: ["Imphal valley forecast", "Paddy water control", "North-East radar"],
    },
    keywords: ["manipur", "imphal", "churachandpur", "मणिपुर"],
  },
  {
    id: "meghalaya",
    name: "Meghalaya",
    hindiName: "मेघालय",
    country: "India",
    capital: "Shillong",
    region: "North-East",
    temperature: 20,
    feelsLike: 20,
    condition: "Intense Orograpic Rain",
    rainChance: 92,
    humidity: 94,
    windSpeed: 16,
    aqi: 18,
    alert: "Red alert for heavy to very heavy rainfall in Cherrapunji-Mawsynram belt",
    advisory: {
      title: "High Rainfall & Landslide Warning",
      status: "Emergency",
      body: "Extreme rainfall expected across southern slopes. Avoid vulnerable hill roads and riverbanks.",
      actions: ["Mawsynram rainfall metrics", "Hill route advisory", "Disaster response contact"],
    },
    keywords: ["meghalaya", "shillong", "cherrapunji", "mawsynram", "tura", "मेघालय"],
  },
  {
    id: "mizoram",
    name: "Mizoram",
    hindiName: "मिज़ोरम",
    country: "India",
    capital: "Aizawl",
    region: "North-East",
    temperature: 23,
    feelsLike: 24,
    condition: "Mist & Occasional Showers",
    rainChance: 54,
    humidity: 85,
    windSpeed: 9,
    aqi: 22,
    advisory: {
      title: "Jhum Cultivation & Slope Management",
      status: "Normal",
      body: "Intermittent showers ensure good soil moisture. Clear terraced drains to prevent topsoil loss.",
      actions: ["Aizawl weather bulletin", "Terraced farming tips", "Road safety alert"],
    },
    keywords: ["mizoram", "aizawl", "lunglei", "मिज़ोरम"],
  },
  {
    id: "nagaland",
    name: "Nagaland",
    hindiName: "नागालैंड",
    country: "India",
    capital: "Kohima",
    region: "North-East",
    temperature: 22,
    feelsLike: 23,
    condition: "Cool Breeze & Passing Rain",
    rainChance: 50,
    humidity: 80,
    windSpeed: 10,
    aqi: 24,
    advisory: {
      title: "Hill Farming & Terrace Irrigation",
      status: "Good",
      body: "Mild hill temperatures and intermittent rainfall create favorable conditions for ginger and cardamom.",
      actions: ["Kohima regional update", "Spice crop guidance", "Hill pass condition"],
    },
    keywords: ["nagaland", "kohima", "dimapur", "mokokchung", "नागालैंड"],
  },
  {
    id: "odisha",
    name: "Odisha",
    hindiName: "ओडिशा",
    country: "India",
    capital: "Bhubaneswar",
    region: "East",
    temperature: 31,
    feelsLike: 37,
    condition: "Squally Winds & Rain Bands",
    rainChance: 78,
    humidity: 86,
    windSpeed: 25,
    aqi: 58,
    alert: "Cyclonic circulation advisory over Bay of Bengal",
    advisory: {
      title: "Bay of Bengal Squall Alert",
      status: "Warning",
      body: "High wind gusts and coastal squalls. Fishermen must hoist warning signals and refrain from sea sorties.",
      actions: ["Coastal wind speed map", "Fishermen warning bulletin", "Bhubaneswar radar"],
    },
    keywords: ["odisha", "orissa", "bhubaneswar", "cuttack", "puri", "rourkela", "ओडिशा"],
  },
  {
    id: "punjab",
    name: "Punjab",
    hindiName: "पंजाब",
    country: "India",
    capital: "Chandigarh",
    region: "North",
    temperature: 32,
    feelsLike: 35,
    condition: "Sunny Intervals & Dry Breeze",
    rainChance: 15,
    humidity: 58,
    windSpeed: 15,
    aqi: 135,
    advisory: {
      title: "Paddy Irrigation & Pesticide Window",
      status: "Good",
      body: "Next 48 hours offer dry weather window. Highly suitable for pesticide spraying in basmati rice fields.",
      actions: ["Check 48-hour dry window", "Basmati pest management", "Tube-well irrigation tips"],
    },
    keywords: ["punjab", "chandigarh", "amritsar", "ludhiana", "jalandhar", "patiala", "ਪੰਜਾਬ", "पंजाब"],
  },
  {
    id: "rajasthan",
    name: "Rajasthan",
    hindiName: "राजस्थान",
    country: "India",
    capital: "Jaipur",
    region: "North",
    temperature: 36,
    feelsLike: 39,
    condition: "Hot & Arid Sunshine",
    rainChance: 8,
    humidity: 42,
    windSpeed: 18,
    aqi: 120,
    advisory: {
      title: "Heat Precautions & Bajra Management",
      status: "Caution",
      body: "High afternoon heat index. Irrigate bajra and guar during early morning to minimize evapotranspiration losses.",
      actions: ["Drip irrigation schedule", "Heat safety advisory", "Jaipur weather map"],
    },
    keywords: ["rajasthan", "jaipur", "jodhpur", "udaipur", "kota", "bikaner", "राजस्थान"],
  },
  {
    id: "sikkim",
    name: "Sikkim",
    hindiName: "सिक्किम",
    country: "India",
    capital: "Gangtok",
    region: "North-East",
    temperature: 18,
    feelsLike: 18,
    condition: "Cool Fog & Intermittent Drizzle",
    rainChance: 68,
    humidity: 87,
    windSpeed: 8,
    aqi: 20,
    alert: "Dense fog on high elevation mountain passes (Nathu La)",
    advisory: {
      title: "Cardamom Orchards & Tourism Advisory",
      status: "Caution",
      body: "Maintain strict road vigilance along North Sikkim highway. Large cardamom drying operations need shelter.",
      actions: ["Nathu La pass status", "Organic cardamom advice", "Gangtok live forecast"],
    },
    keywords: ["sikkim", "gangtok", "namchi", "pelling", "सिक्किम"],
  },
  {
    id: "tamil-nadu",
    name: "Tamil Nadu",
    hindiName: "तमिलनाडु",
    country: "India",
    capital: "Chennai",
    region: "South",
    temperature: 34,
    feelsLike: 39,
    condition: "Humid Sunshine & Sea Breeze",
    rainChance: 25,
    humidity: 75,
    windSpeed: 17,
    aqi: 60,
    advisory: {
      title: "Kuruvai Paddy & Coastal Heat Advisory",
      status: "Normal",
      body: "Evening sea breeze cools coastal areas. Cauvery delta farmers should irrigate in mornings to conserve water.",
      actions: ["Chennai sea breeze forecast", "Cauvery delta report", "Urban heat guidelines"],
    },
    keywords: ["tamil nadu", "tamilnadu", "chennai", "coimbatore", "madurai", "tiruchirappalli", "தமிழ்நாடு", "तमिलनाडु"],
  },
  {
    id: "telangana",
    name: "Telangana",
    hindiName: "तेलंगाना",
    country: "India",
    capital: "Hyderabad",
    region: "South",
    temperature: 31,
    feelsLike: 34,
    condition: "Scattered Clouds & Passing Showers",
    rainChance: 35,
    humidity: 68,
    windSpeed: 16,
    aqi: 70,
    advisory: {
      title: "Cotton & Maize Advisory",
      status: "Good",
      body: "Scattered afternoon showers provide optimal soil moisture for cotton boll development. Good spraying window.",
      actions: ["Hyderabad radar", "Cotton bollworm alert", "Soil moisture tracker"],
    },
    keywords: ["telangana", "hyderabad", "warangal", "nizamabad", "karimnagar", "తెలంగాణ", "तेलंगाना"],
  },
  {
    id: "tripura",
    name: "Tripura",
    hindiName: "त्रिपुरा",
    country: "India",
    capital: "Agartala",
    region: "North-East",
    temperature: 28,
    feelsLike: 32,
    condition: "Cloudy & Thundershowers",
    rainChance: 65,
    humidity: 84,
    windSpeed: 12,
    aqi: 38,
    advisory: {
      title: "Rubber Plantation & Rice Advisory",
      status: "Moderate",
      body: "Install rain-guards on rubber trees to safeguard latex harvest. Ensure drainage channels are clear in lowlands.",
      actions: ["Rubber tapping guidelines", "Agartala forecast", "Flood water discharge report"],
    },
    keywords: ["tripura", "agartala", "udaipur tripura", "त्रिपुरा"],
  },
  {
    id: "uttar-pradesh",
    name: "Uttar Pradesh",
    hindiName: "उत्तर प्रदेश",
    country: "India",
    capital: "Lucknow",
    region: "Central",
    temperature: 33,
    feelsLike: 37,
    condition: "Partly Cloudy & Humid",
    rainChance: 32,
    humidity: 69,
    windSpeed: 13,
    aqi: 128,
    advisory: {
      title: "Sugarcane & Paddy Water Management",
      status: "Normal",
      body: "Humid weather with localized showers. Top-dress sugarcane with bio-fertilizers and spray during morning hours.",
      actions: ["Sugarcane pest advisory", "Lucknow air quality", "Gangetic basin outlook"],
    },
    keywords: ["uttar pradesh", "up", "lucknow", "kanpur", "varanasi", "agra", "prayagraj", "उत्तर प्रदेश"],
  },
  {
    id: "uttarakhand",
    name: "Uttarakhand",
    hindiName: "उत्तराखंड",
    country: "India",
    capital: "Dehradun",
    region: "North",
    temperature: 24,
    feelsLike: 25,
    condition: "Mountain Rain & Cloudburst Watch",
    rainChance: 72,
    humidity: 82,
    windSpeed: 11,
    aqi: 36,
    alert: "Moderate landslide risk along Char Dham pilgrimage routes",
    advisory: {
      title: "Char Dham Yatra & Hill Safety",
      status: "Warning",
      body: "Heavy spells expected in Chamoli and Rudraprayag. Pilgrims should confirm road clearance before hill travel.",
      actions: ["Char Dham road clearance", "Dehradun weather radar", "Disaster management portal"],
    },
    keywords: ["uttarakhand", "dehradun", "haridwar", "rishikesh", "nainital", "kedarnath", "badrinath", "उत्तराखंड"],
  },
  {
    id: "west-bengal",
    name: "West Bengal",
    hindiName: "पश्चिम बंगाल",
    country: "India",
    capital: "Kolkata",
    region: "East",
    temperature: 31,
    feelsLike: 37,
    condition: "Humid with Rain & Thunder",
    rainChance: 70,
    humidity: 85,
    windSpeed: 18,
    aqi: 66,
    alert: "Thunderstorm with gusty winds predicted over Gangetic West Bengal",
    advisory: {
      title: "Aman Paddy & Jute Advisory",
      status: "Moderate",
      body: "Adequate moisture for Aman paddy tillering. Complete jute retting in clean slow-flowing water bodies.",
      actions: ["Kolkata radar live", "Jute retting best practices", "Aman paddy fertilizer tips"],
    },
    keywords: ["west bengal", "bengal", "kolkata", "calcutta", "darjeeling", "siliguri", "howrah", "পশ্চিমবঙ্গ", "पश्चिम बंगाल"],
  },
  // UTs
  {
    id: "delhi",
    name: "Delhi NCR",
    hindiName: "दिल्ली एनसीआर",
    country: "India",
    capital: "New Delhi",
    region: "North",
    temperature: 32,
    feelsLike: 35,
    condition: "Partly Cloudy with Humid Intervals",
    rainChance: 24,
    humidity: 68,
    windSpeed: 14,
    aqi: 148,
    advisory: {
      title: "Urban Atmosphere & AQI Guidance",
      status: "Caution",
      body: "Moderate air quality. Afternoon heat index reaches 35°C; keep hydrated and avoid prolonged outdoor exertion.",
      actions: ["Delhi AQI breakdown", "Traffic weather heat map", "7-day NCR outlook"],
    },
    keywords: ["delhi", "new delhi", "ncr", "delhi ncr", "नई दिल्ली", "दिल्ली"],
  },
  {
    id: "jammu-kashmir",
    name: "Jammu & Kashmir",
    hindiName: "जम्मू और कश्मीर",
    country: "India",
    capital: "Srinagar / Jammu",
    region: "North",
    temperature: 22,
    feelsLike: 22,
    condition: "Mild Alpine Breeze & Light Showers",
    rainChance: 38,
    humidity: 64,
    windSpeed: 10,
    aqi: 30,
    advisory: {
      title: "Apple & Saffron Valley Update",
      status: "Good",
      body: "Cool conditions support saffron corm sprouting in Pampore. Apple harvesting in Sopore is well on schedule.",
      actions: ["Srinagar live weather", "Saffron valley guide", "Mughal Road status"],
    },
    keywords: ["jammu", "kashmir", "srinagar", "jammu & kashmir", "jammu and kashmir", "जम्मू", "कश्मीर"],
  },
  {
    id: "ladakh",
    name: "Ladakh",
    hindiName: "लद्दाख",
    country: "India",
    capital: "Leh",
    region: "North",
    temperature: 14,
    feelsLike: 12,
    condition: "Crisp High-Altitude Clear Skies",
    rainChance: 5,
    humidity: 28,
    windSpeed: 18,
    aqi: 15,
    alert: "Sub-zero overnight temperatures in high mountain passes",
    advisory: {
      title: "High Altitude UV & Frost Warning",
      status: "Notice",
      body: "Very high UV index (10+) during daylight with sudden freezing temperatures at night. Carry UV protection and cold gear.",
      actions: ["Khardung La pass weather", "Leh cold wave alert", "UV protection checklist"],
    },
    keywords: ["ladakh", "leh", "kargil", "लद्दाख"],
  },
];

export function findMatchingIndianState(query: string): IndianStateInfo | undefined {
  const normalized = query.toLowerCase().trim();
  return INDIAN_STATES_DATA.find((state) => {
    if (normalized.includes(state.name.toLowerCase())) return true;
    if (normalized.includes(state.capital.toLowerCase())) return true;
    return state.keywords.some((kw) => normalized.includes(kw.toLowerCase()));
  });
}
